# Generated by Django 3.2.18 on 2023-05-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ours_vote',
            field=models.FloatField(default=0),
        ),
    ]
