# Generated by Django 3.2.18 on 2023-05-24 03:18

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.TextField(blank=True, verbose_name=movies.models.Movie),
        ),
    ]
