# Generated by Django 3.2.18 on 2023-05-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
