# Generated by Django 3.2.18 on 2023-05-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='like_reveiws',
            new_name='like_reviews',
        ),
    ]
