# Generated by Django 3.2.18 on 2023-05-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_coin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='coin',
            new_name='coins',
        ),
    ]
